POST http://localhost:3003/api/blogs
Content-Type: application/json


{
  "title": "When swimming home ",
  "author": "Tim Son",
  "likes": "65",
  "url": "fountain",
  "userId":"62177e3a359aa68474ed1fa6"
}