POST http://localhost:3003/api/blogs
Content-Type: application/json


{
  "title": "When we are coming home ",
  "author": "John Tim",
  "likes": "45",
  "url": "mountain",
  "userId":"6215fcd3a1cb8e23633ce982"
}